version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: Build(deps-py)
  groups:
    dependencies:
      patterns:
        - "*"
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  allow:
    - dependency-type: "direct"
  open-pull-requests-limit: 10
  commit-message:
    prefix: Build(deps-rs)
  ignore:
    - dependency-name: "byteorder"
    - dependency-name: "wasm-bindgen"
    - dependency-name: "once_cell"
    - dependency-name: "chrono"
    - dependency-name: "js-sys"
    - dependency-name: "web-sys"
  groups:
    dependencies:
      patterns:
        - "*"
- package-ecosystem: "github-actions"
  directory: "/"
  commit-message:
    prefix: Build(ci)
  schedule:
    interval: weekly
