# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

conda:
  environment: doc/environment.yml

python:
  # NOTE: doc/environment.yml specifies python=3.10, which is needed
  # b/c of a pip problem; see
  # https://github.com/sourmash-bio/sourmash/issues/2139
  # this 'version' setting is effectively ignored, AFAICT. -- CTB 7/24/22
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
  system_packages: true
