name: sourmash_dev
channels:
  - conda-forge
dependencies:
  - clangdev >=16.0.6,<16.1
  - cxx-compiler >=1.7.0,<1.8
  - git 2.41.0.*
  - libclang >=16.0.6,<16.1
  - pandoc 3.1.3.*
  - python 3.10.*
  - rust >=1.80.0,<1.81
  - tox >=4.11.0,<5
