[project]
name = "sourmash"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
clangdev = ">=16.0.6,<17.1"
cxx-compiler = ">=1.7.0,<1.8"
git = "2.41.0.*"
libclang = ">=16.0.6,<17.1"
pandoc = "3.1.3.*"
python = "3.10.*"
rust = ">=1.76.0,<1.77"
tox = ">=4.11.0,<5"
conda = ">=23.11.0,<23.12"
