name: codspeed-benchmarks

on:
  # Run on pushes to the main branch
  push:
    branches:
      - "latest"
  # Run on pull requests
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks-rust:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo codspeed build -p sourmash

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: "cd src/core && cargo codspeed run"
          token: ${{ secrets.CODSPEED_TOKEN }}
