name: Hypothesis tests

permissions:
  contents: read

on:
  push:
    branches: [latest]
  pull_request:
  merge_group:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run Hypothesis tests
        run: tox -e hypothesis,coverage

      - name: Upload Python coverage to codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          flags: hypothesis-py
          fail_ci_if_error: true
          files: .tox/coverage.xml
          use_pypi: true
